apiVersion: v1
kind: Pod
metadata:
  name: nginx-tolerated
  labels:
    project: roboshop
    environment: dev
    purpose: poc
spec:
  containers:
  - name: nginx
    image: nginx
  tolerations:        # toleration is set on POD to schedule the POD on the TAINTED NODE.
  - key: "project"   # but there is not gurantee that the TOLERATED POD will schudule only on the TAINTED NODE. if will we just use TOLERATION
    operator: "Equal"  # there is a chance that this TOLERATED POD will be scheduled on any avaible NODES not just TAINTED NODE.
    value: "roboshop"       
    effect: "NoExecute"
  # selectors
  nodeSelector:   # we want to work "TOLERATION for gurantee" on POD, then we have to use SELECTORS also like "nodeselectores"
    project: roboshop

#  k8's will not schudule any pods on the TAINTED NODE
# taint is a label put on a node that says: KEEP AWAY, UNLESS YOU HAVE A KEY,
# TAINT acts like a LOCK or DO NOT DISCTURB sign on the server

# TAINT = applied on the NODE, tells the cluster to keep pods away unless they have permission
# TOLERATION = applied on the POD, gives the pod permission to land on a tainted node