apiVersion: v1
kind: Pod
metadata:
  name: with-node-anti-affinity
  labels:
    app: web
spec:
  affinity:
    nodeAffinity:
      # hard filter
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - us-east-1d  # pod will be schulded in this 1 of the 2 avaibility zones, this is the advantage of nodeAffinity
            - us-east-1c  # pod will be schulded in this 1 of the 2 avaibility zones, this is the advantage of nodeAffinity

      # In = MUST schedule on these nodes (Pod stays Pending if unavailable).
      # NotIn = MUST NOT schedule on these nodes (Pod stays Pending if no other nodes exist).

      # soft filter
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: topology.kubernetes.io/zone  # the weight is 100 so scheduler picked us-east-1c to schudule pod 
            operator: NOTIn # NotIN is anti affinity
            values:
            - us-east-1c

      - weight: 60
        preference:
          matchExpressions:
          - key: topology.kubernetes.io/zone # the weight is 60 so scheduler didnt picked on us-east-1d to schudule pod 
            operator: In
            values:
            - us-east-1d
        # In = PREFERS these nodes (adds weight points).
        # NotIn = AVOIDS these nodes (adds weight points to all other nodes).
  containers:
  - name: nginx
    image: nginx:latest

    